config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboards#show'
  get 'dashboard', to: 'dashboards#show'

  get 'dashboard/member_borrows', to: 'dashboards#member_borrows'
  get 'dashboard/all_borrows', to: 'dashboards#all_borrows'

  namespace :admin do
    resources :users
  end

  resources :borrows, only: [:create, :update] do
    member do
      put 'return_book'
    end
  end

  resources :books
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  ITEMS = 5

  def show
    @url = dashboard_path

    if current_user.has_role?(:member)
      authorize! :read, :member_dashboard
      load_books
      @total_books = Book.count
      render :member
    else
      authorize! :read, :librarian_dashboard
      load_books
      @total_books = Book.count
      render :librarian
    end
  end

  def all_borrows
    authorize! :read, :librarian_dashboard
    load_borrows
    @url = dashboard_all_borrows_path
  end

  def member_borrows
    authorize! :read, :member_dashboard
    load_user_borrows
    @url = dashboard_member_borrows_path
  end

  private

  def load_books
    books = params[:search].present? ? Book.search(params[:search]) : Book.all
    @pagy, @books = pagy(books, items: ITEMS)
  end

  def load_borrows
    borrows = Borrow.not_done.includes(:user, :book)
    @total_borrows = borrows.count
    borrows = borrows.search(params[:search]) if params[:search].present?
    @pagy, @borrows = pagy(borrows.order(due_date: :desc), items: ITEMS)
  end

  def load_user_borrows
    user_borrows = current_user.borrows.not_done
    @total_borrows = user_borrows.count
    user_borrows = user_borrows.search(params[:search]) if params[:search].present?
    @pagy, @borrows = pagy(user_borrows.order(due_date: :desc), items: ITEMS)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/tabs/_books.html.slim
h2.text-2xl.font-bold.mb-2 Total Books
p.text-lg = @total_books

= link_to 'New Book', new_book_path, class: 'mt-4 inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700'

h3.text-xl.font-bold.mt-4.mb-2 Book List

- if @books.any?
  div.overflow-x-auto
    table.min-w-full.bg-white
      thead
        tr
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Title
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Author
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Genre
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 ISBN
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Total Copies
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Actions
      tbody
        - @books.each do |book|
          tr
            td.py-2.px-4.border-b.text-center = book.title
            td.py-2.px-4.border-b.text-center = book.author
            td.py-2.px-4.border-b.text-center = book.genre
            td.py-2.px-4.border-b.text-center = book.isbn
            td.py-2.px-4.border-b.text-center = book.total_copies
            td.py-2.px-4.border-b
              = link_to 'Show', book, class: 'text-blue-500 hover:underline'
              = link_to 'Edit', edit_book_path(book), class: 'ml-2 text-blue-500 hover:underline'
              = link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-2 text-red-500 hover:underline'

  = render partial: '/shared/pagination', locals: { pagy: @pagy }

- else
  p No books available.

app/views/dashboards/tabs/_borrowed_books.html.slim
h2.text-2xl.font-bold.mb-2 Total Borrows
p.text-lg = @total_borrows


h3.text-xl.font-bold.mt-4.mb-2 Borrow List
- if @borrows.any?
  div.overflow-x-auto
    table.min-w-full.bg-white
      thead
        tr
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Title
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Author
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Genre
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Borrow date
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Due date
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 User
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Borrow status
          th.py-2.px-4.bg-gray-200.font-bold.uppercase.text-sm.text-gray-600 Action
      tbody
        - @borrows.each do |borrow|
          tr class="#{borrow_book_class(borrow)}"
            td.py-2.px-4.border-b.text-center = borrow.book.title
            td.py-2.px-4.border-b.text-center = borrow.book.author
            td.py-2.px-4.border-b.text-center = borrow.book.genre
            td.py-2.px-4.border-b.text-center = borrow.borrowed_at.strftime("%d/%m/%Y")
            td.py-2.px-4.border-b.text-center = borrow.due_date.strftime("%d/%m/%Y")
            td.py-2.px-4.border-b.text-center = borrow.user.email
            td.text-center = borrow.status
            td.py-2.px-4.border-b
              = button_to 'Mark as returned', return_book_borrow_path(id: borrow.id), method: :put, remote: true, class: 'hover:underline'


  = render partial: '/shared/pagination', locals: { pagy: @pagy }

- else
  p No books available.