config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboards#show'
  get 'dashboard', to: 'dashboards#show'

  get 'dashboard/member_borrows', to: 'dashboards#member_borrows'
  get 'dashboard/all_borrows', to: 'dashboards#all_borrows'

  namespace :admin do
    resources :users
  end

  resources :borrows, only: [:create, :update] do
    member do
      put 'return_book'
    end
  end

  resources :books
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                 :bigint           not null, primary key
#  author             :string           not null
#  available_copies   :integer
#  check_digit        :string           not null
#  ean_prefix         :string           not null
#  genre              :string
#  publication        :string           not null
#  registrant         :string           not null
#  registration_group :string           not null
#  title              :string           not null
#  total_copies       :integer          not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Book < ApplicationRecord
  has_many :borrows

  validates :ean_prefix, length: { is: 3 }, numericality: { only_integer: true }
  validates :registration_group, length: { in: 1..5 }, numericality: { only_integer: true }
  validates :registrant, length: { in: 1..7 }, numericality: { only_integer: true }
  validates :publication, length: { in: 1..6 }, numericality: { only_integer: true }
  validates :check_digit, length: { is: 1 }, numericality: { only_integer: true }
  validate :valid_isbn_length
  validates :title, :author, :total_copies, presence: true

  before_create :set_available_copies

  scope :search, ->(term) { where('title ILIKE ? OR author ILIKE ? OR genre ILIKE ?', "%#{term}%", "%#{term}%", "%#{term}%") }

  def isbn
    "#{ean_prefix}-#{registration_group}-#{registrant}-#{publication}-#{check_digit}"
  end

  private

  def set_available_copies
    return unless available_copies.nil?

    self.available_copies = total_copies
  end

  def valid_isbn_length
    total_digits = ean_prefix.length + registration_group.length + registrant.length + publication.length + check_digit.length

    errors.add(:base, 'ISBN must have 13 digits') if total_digits != 13
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to dashboard_path, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to dashboard_path, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :genre, :ean_prefix, :registration_group, :registrant, :publication, :check_digit, :total_copies)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.slim
div id="#{dom_id book}"
  p
    strong Title:
    =< book.title
  p
    strong Author:
    =< book.author
  p
    strong Genre:
    =< book.genre
  p
    strong Ean prefix:
    =< book.ean_prefix
  p
    strong Registration group:
    =< book.registration_group
  p
    strong Registrant:
    =< book.registrant
  p
    strong Publication:
    =< book.publication
  p
    strong Check digit:
    =< book.check_digit
  p
    strong Total copies:
    =< book.total_copies

app/views/books/_form.html.slim
= form_with(model: book) do |f|
  - if book.errors.any?
    div style="color: red"
      h2 = "#{pluralize(book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - book.errors.each do |error|
          li = error.full_message

  .mt-2
    .grid.grid-cols-1.gap-x-6.gap-y-8.sm:grid-cols-4
      .mb-4.sm:col-span-2
        = f.label :title, class: 'block text-gray-700 text-sm font-bold mb-2'
        = f.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
      .mb-4.sm:col-span-2
        = f.label :author, class: 'block text-gray-700 text-sm font-bold mb-2'
        = f.text_field :author, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
      .mb-4.sm:col-span-2
        = f.label :genre, class: 'block text-gray-700 text-sm font-bold mb-2'
        = f.text_field :genre, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
      .mb-4.sm:col-span-2
        = f.label :total_copies, class: 'block text-gray-700 text-sm font-bold mb-2'
        = f.number_field :total_copies, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

  .mt2
    div.block.text-gray-700.text-md.font-bold.mb-2 ISBN
    .grid.grid-cols-1.gap-x-6.gap-y-8.sm:grid-cols-6
      .sm:col-span-1
        = f.label :ean_prefix, class: 'block text-gray-700 text-sm font-bold mb-2'
        .mt-2
          = f.text_field :ean_prefix, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

      .sm:col-span-1
        = f.label :registration_group, class: 'block text-gray-700 text-sm font-bold mb-2'
        .mt-2
          = f.text_field :registration_group, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

      .sm:col-span-1
        = f.label :registrant, class: 'block text-gray-700 text-sm font-bold mb-2'
        .mt-2
          = f.text_field :registrant, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

      .sm:col-span-1
        = f.label :publication, class: 'block text-gray-700 text-sm font-bold mb-2'
        .mt-2
          = f.text_field :publication, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

      .sm:col-span-1
        = f.label :check_digit, class: 'block text-gray-700 text-sm font-bold mb-2'
        .mt-2
          = f.text_field :check_digit, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'

  .mt-8.flex.items-center.justify-between
    = f.submit 'Submit', class: 'btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline'

app/views/books/edit.html.slim
h1.text-2xl.font-bold.mb-4 Edit Book

= render 'form', book: @book

= link_to 'Back', root_path, class: 'mt-4 inline-block bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700'

app/views/books/index.html.slim
/ app/views/books/index.html.slim
h1.text-2xl.font-bold.mb-4 Books

.table-auto.w-full
  thead
    tr
      th.px-4.py-2.border Title
      th.px-4.py-2.border Author
      th.px-4.py-2.border Genre
      th.px-4.py-2.border ISBN
      th.px-4.py-2.border Actions

  tbody
    - @books.each do |book|
      tr
        td.px-4.py-2.border= book.title
        td.px-4.py-2.border= book.author
        td.px-4.py-2.border= book.genre
        td.px-4.py-2.border= book.isbn
        td.px-4.py-2.border
          = link_to 'Show', book, class: 'text-blue-500 hover:underline'
          = link_to 'Edit', edit_book_path(book), class: 'ml-2 text-blue-500 hover:underline'
          = link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-2 text-red-500 hover:underline'

= link_to 'New Book', new_book_path, class: 'mt-4 inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700'

app/views/books/new.html.slim
h1.text-2xl.font-bold.mb-4 New Book

= render 'form', book: @book

= link_to 'Back', root_path, class: 'mt-4 inline-block bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700'

app/views/books/show.html.slim
/ app/views/books/show.html.slim
h1.text-2xl.font-bold.mb-4 Book Details

.table-auto.w-full
  tbody
    tr
      td.px-4.py-2.border Title
      td.px-4.py-2.border= @book.title
    tr
      td.px-4.py-2.border Author
      td.px-4.py-2.border= @book.author
    tr
      td.px-4.py-2.border Genre
      td.px-4.py-2.border= @book.genre
    tr
      td.px-4.py-2.border ISBN
      td.px-4.py-2.border= @book.isbn

= link_to 'Edit', edit_book_path(@book), class: 'mt-4 inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700'
= link_to 'Back', books_path, class: 'mt-4 inline-block bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700'